# -*- coding: utf-8 -*-
import sys
import subprocess
import os

"""
/***************************************************************************
 IatTeste
                                 A QGIS plugin
 Este plugin serve para facilitar o workflow das análises no âmbito do Instituto.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-30
        copyright            : (C) 2026 by IAT
        email                : est.pedromoraes@iat.pr.gov.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def checar_e_instalar_dependencias():
    """Verifica se o Google está instalado. Se não, acha o python correto e instala."""
    try:
        import googleapiclient
        import google.auth
    except ImportError:
        from qgis.PyQt.QtWidgets import QMessageBox
        
        aviso = QMessageBox()
        aviso.setWindowTitle("IatTeste - Configuração Inicial")
        aviso.setText(
            "Bem-vindo(a)!\n\n"
            "Parece que é a primeira vez que você roda este plugin.\n"
            "Para acessar as planilhas, precisamos baixar as bibliotecas do Google.\n\n"
            "Uma tela preta vai se abrir. POR FAVOR, AGUARDE ELA FECHAR SOZINHA."
        )
        aviso.setIcon(QMessageBox.Information)
        aviso.exec_()

        if sys.platform == 'win32':
            python_exe = os.path.join(sys.prefix, 'python.exe')
        else:
            python_exe = sys.executable
            
        pacotes = [
            'google-api-python-client', 
            'google-auth-httplib2', 
            'google-auth-oauthlib'
        ]
        
        comando = [python_exe, '-m', 'pip', 'install'] + pacotes + ['--user']

        try:
            if os.name == 'nt':
                CREATE_NEW_CONSOLE = 0x00000010
                subprocess.call(comando, creationflags=CREATE_NEW_CONSOLE)
            else:
                subprocess.call(comando)
            
            QMessageBox.information(
                None, 
                "Instalação Concluída", 
                "Tudo pronto! As bibliotecas foram instaladas.\n\n"
                "Por favor, REINICIE O QGIS para que as alterações façam efeito."
            )
        except Exception as e:
            QMessageBox.critical(None, "Erro", f"Falha ao tentar instalar: {e}")

# Executa a checagem no exato momento em que o plugin é lido
checar_e_instalar_dependencias()

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IatTeste class from file IatTeste.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .iat_teste import IatTeste

    return IatTeste(iface)
