# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IatTesteDockWidget
                                 A QGIS plugin
 Este plugin serve para facilitar o workflow das análises no âmbito do Instituto.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by IAT
        email                : est.pedromoraes@iat.pr.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'iat_teste_dockwidget_base.ui'))


class IatTesteDockWidgetBase(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(IatTesteDockWidgetBase, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.btn_executar.clicked.connect(self.executar_analise)

        def executar_analise(self):
            texto_pesquisa = self.valor_pesq.text()
            tipo_filtro = self.sel_campo.currentText()

            if tipo_filtro in ["CPF/CNPJ","Protocolo"]:
                texto_limpo = texto_pesquisa.replace(".", "").replace("-", "").replace("/", "")
            else:
                texto_limpo = texto_pesquisa

            print(f"Sucesso! Buscando por {texto_limpo} no campo {tipo_filtro}.")

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
