# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IatTesteDockWidget
                                 A QGIS plugin
 Este plugin serve para facilitar o workflow das análises no âmbito do Instituto.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by IAT
        email                : est.pedromoraes@iat.pr.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import QgsVectorLayer, QgsFeature, QgsSymbol, QgsSingleSymbolRenderer, QgsFeatureRequest, QgsMapLayerProxyModel, QgsMapLayerType, QgsProject, QgsGeometry
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtWidgets import QTableWidgetItem, QHeaderView
from qgis.PyQt.QtCore import pyqtSignal
from qgis.gui import QgsMapToolIdentifyFeature
from qgis.utils import iface

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'iat_teste_dockwidget_base.ui'))

DIALOG_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'analise_mont.ui'))


class IatTesteDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(IatTesteDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Não mexa em qualquer coisa acima deste ponto, a menos que saiba exatamente o que está fazendo!
        # O código acima foi gerado automaticamente e é responsável por configurar a interface gráfica e as demais funções. 

        self.btn_exec.setDefault(True)

        # self.sel_camada.setFilters(QgsMapLayerProxyModel.VectorLayer)

        # Executa a análise se o usuário clicar no botão ou apertar Enter.
        self.btn_exec.clicked.connect(self.executar_analise)
        self.valor_pesq.returnPressed.connect(self.executar_analise)

        # O botão de seleção de rio é feito para facilitar a seleção do rio, no lugar do usuário precisar
        # identificar a camada e extrair o ottocódigo manualmente, usando a ferramenta de seleção do QGIS.
        self.btn_sel_rio.clicked.connect(self.ativar_selecao_rio)

        # Botão de análise montante. Ele conecta a função com a lógica de análise de montante, que está em
        # estágios iniciais de implementação, mas a ideia é que ele utilize os códigos de rio e bacia para
        # realizar a seleção automática das ottobacias a montante e o predicado geométrico de contenção
        # para determinar os pontos outorgados e a vazão indisponível.
        self.btn_exec_mont.clicked.connect(lambda: self.analise_montante(self.disp_cod_rio.text(), self.disp_cod_bac.text()))

        self.vazao_outorgada = 0.0
        self.btn_ger_memcalc.clicked.connect(lambda: self.gerar_memorial(self.vazao_outorgada))

        # Configurações da tabela de resultados
        self.tabela.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabela.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabela.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabela.setColumnHidden(0, True)
        self.tabela.cellDoubleClicked.connect(self.zoom_pto)

        self.amont_atual = 0.0
        self.acont_atual = 0.0
        self.sel_qesp.valueChanged.connect(self.atualizar_calculos)
        self.sel_area_prop.valueChanged.connect(self.atualizar_calculos)
        self.radioBtn_100.toggled.connect(self.atualizar_calculos)
        self.radioBtn_80.toggled.connect(self.atualizar_calculos)
        self.radioBtn_50.toggled.connect(self.atualizar_calculos)

        # Lógica de filtrar camadas apenas para aquelas que contém o campo "nr_e_protocolo", que é o campo mais presente e utilizado para as análises. Assim, evitamos erros de camadas sem esse campo e facilitamos a vida do usuário.
        # self.filtrar_camadas_campo("nr_e_protocolo")

        # QgsProject.instance().layersAdded.connect(lambda: self.filtrar_camadas_campo("nr_e_protocolo"))
        self.atualizar_todos_filtros()
        QgsProject.instance().layersAdded.connect(self.atualizar_todos_filtros)

    # Função que filtra as camadas disponíveis, mostrando apenas aquelas relevantes
    def filtrar_camadas_campo(self, box_alvo, lista_campos):

        camadas_para_filtrar = []

        todas_camadas = QgsProject.instance().mapLayers().values()
        campos_buscados = [campo.lower() for campo in lista_campos]

        # Itera sobre todas as camadas do projeto e verifica se são do tipo vetor e se possuem o campo específico. Se não atenderem a esses critérios, são adicionadas à lista de camadas a serem filtradas.
        for camada in todas_camadas:
            if camada.type() != QgsMapLayerType.VectorLayer:
                camadas_para_filtrar.append(camada)
                continue

            nomes_das_colunas = [campo.name().lower() for campo in camada.fields()]
            
            if not any(campo_buscado in nomes_das_colunas for campo_buscado in campos_buscados):
                camadas_para_filtrar.append(camada)
            
            # Envia a lista de camadas a serem filtradas para o widget de seleção de camadas, que irá ocultá-las da lista de opções disponíveis para o usuário.
            box_alvo.setExceptedLayerList(camadas_para_filtrar)

    def atualizar_todos_filtros(self, *args):
        try:
            self.filtrar_camadas_campo(self.sel_camada, ["nr_e_protocolo", "PROTOCOLO"])
            self.filtrar_camadas_campo(self.sel_camada_rio, ["noriocomp"])
            self.filtrar_camadas_campo(self.sel_camada_ottobacias, ["shape_area"])
        except Exception as e:
            print(f"Erro ao atualizar filtros: {e}")

    # Componente principal do widget, onde ocorre a lógica de análise dos dados. Ele verifica se a camada selecionada é válida, constrói uma expressão de filtro com base no tipo de pesquisa escolhida e no valor digitado, e então executa a consulta na camada para obter os resultados correspondentes. Os resultados são exibidos em uma tabela, e o usuário pode clicar duas vezes em um resultado para dar zoom no ponto correspondente no mapa.
    def executar_analise(self):

        # Recebe os dados dos campos preenchidos e selecionados. O valor da pesquisa é limpo de caracteres especiais caso seja do tipo CPF/CNPJ ou Protocolo, para garantir que a consulta seja feita de forma correta, independentemente do formato em que o usuário tenha digitado o valor.
        texto_pesquisa = self.valor_pesq.text().strip()
        tipo_filtro = self.sel_campo.currentText()
        camada = self.sel_camada.currentLayer()

        # Erros. O sistema verifica se a camada selecionada é válida, se é do tipo vetor, e se o valor de pesquisa foi preenchido. Se alguma dessas condições não for atendida, uma mensagem de aviso é exibida para o usuário, indicando o problema específico.
        if not camada:
            QtWidgets.QMessageBox.warning(self, "Erro", "Selecione uma camada válida.")
            return
        if camada.type() != QgsMapLayerType.VectorLayer:
            QtWidgets.QMessageBox.warning(self, "Erro", "A camada selecionada deve ser do tipo pontos ou vetor.")
            return
        if not texto_pesquisa:
            QtWidgets.QMessageBox.warning(self, "Erro", "Digite um valor para pesquisa.")
            return

        # Verifica se a camada utilizada possui o campo de CPF/CNPJ, para evitar erros caso o usuário não tenha
        # acesso à base restrita do IAT.
        has_cpf_cnpj = camada.fields().indexOf("nr_cpf_cnpj") != -1

        # Realiza a limpeza do valor de pesquisa, removendo caracteres especiais como pontos, traços e barras, caso o tipo de filtro seja CPF/CNPJ ou Protocolo.
        # A base de dados possui valores sem esses caracteres especiais, então a pesquisa é feita sem eles.
        if tipo_filtro in ["CPF/CNPJ","Protocolo"]:
                texto_limpo = texto_pesquisa.replace(".", "").replace("-", "").replace("/", "")
        else:
                texto_limpo = texto_pesquisa

        # Lógica de seleção de campos. Associa os valores filtro a campos específicos que a base de dados possui.
        # A intenção é que no futuro esses campos sejam personalizáveis, mas por ora são fixos para facilitar o uso e evitar erros de campos inexistentes.
        campo_selecionado = ""
        if tipo_filtro == "CPF/CNPJ":
            campo_selecionado = "nr_cpf_cnpj"
        elif tipo_filtro == "Protocolo":
            campo_selecionado = "nr_e_protocolo"
        elif tipo_filtro == "Nome":
            campo_selecionado = "nm_requerente"
        elif tipo_filtro == "Portaria":
            campo_selecionado = "nr_portaria"

        # Gera a expressão SQL para busca. O operador ILIKE existe para realizar uma busca que não diferencia maiúsculas de minúsculas, e os caracteres % são curingas que permitem encontrar o valor de pesquisa em qualquer parte do campo, facilitando a localização dos resultados mesmo que o usuário não saiba exatamente como o valor está formatado na base de dados.
        expressao = f"\"{campo_selecionado}\" ILIKE '%{texto_limpo}%'"

        # Imprime a expressão no console, para depuração.
        print(f"Expressão de filtro: {expressao}")

        # Executa a consulta na camada usando a expressão gerada.
        request = QgsFeatureRequest().setFilterExpression(expressao)
        features = camada.getFeatures(request)

        # Construtores de tabela de resultados.
        self.tabela.setColumnCount(5)
        self.tabela.setHorizontalHeaderLabels(["ID", "CPF/CNPJ", "Protocolo", "Nome", "Portaria"])

        header = self.tabela.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QHeaderView.Interactive)
        header.setSectionResizeMode(3, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QHeaderView.Stretch)

        # Esconde a coluna de ID, que é utilizada apenas para lógica interna, e a camada de CPF/CNPJ se a base
        # de dados utilizada não a possuir.
        self.tabela.setColumnHidden(0, True)
        self.tabela.setColumnHidden(1, not has_cpf_cnpj)

        self.tabela.setRowCount(0)
        linha = 0

        encontrou_resultados = False

        # Para cada resultado encontrado, os dados são extraídos dos campos relevantes e inseridos na tabela de resultados. O ID da feição é mantido oculto na tabela, mas é utilizado para permitir que o usuário dê zoom no ponto correspondente no mapa ao clicar duas vezes em um resultado.
        for feature in features:
            encontrou_resultados = True
            id_feature = str(feature.id())

            if has_cpf_cnpj:
                val_cpf_cnpj = str(feature["nr_cpf_cnpj"])
            else:
                val_cpf_cnpj = "Campo não disponível"
            val_protocolo = str(feature["nr_e_protocolo"])
            val_nome = str(feature["nm_requerente"])
            val_portaria = str(feature["nr_portaria"])

            self.tabela.insertRow(linha)
            self.tabela.setItem(linha, 0, QTableWidgetItem(id_feature))
            self.tabela.setItem(linha, 1, QTableWidgetItem(val_cpf_cnpj))
            self.tabela.setItem(linha, 2, QTableWidgetItem(val_protocolo))
            self.tabela.setItem(linha, 3, QTableWidgetItem(val_nome))
            self.tabela.setItem(linha, 4, QTableWidgetItem(val_portaria))

            linha += 1

        # Mostra uma caixa de aviso caso o valor não tenha sido encontrado.
        if not encontrou_resultados:
            QtWidgets.QMessageBox.information(self, "Resultados", "Nenhum resultado encontrado.")

    # Função que permite dar zoom no ponto correspondente no mapa ao clicar duas vezes em um resultado na tabela. Ela seleciona a feição correspondente na camada e ajusta a visualização do mapa para focar nela, além de destacar a feição por um breve período para facilitar sua localização.
    def zoom_pto(self, linha, coluna):

        # Lógica de seleção.
        camada = self.sel_camada.currentLayer()
        if not camada:
            return
        
        id_item = self.tabela.item(linha, 0)
        if not id_item:
            return

        id_feature = int(id_item.text())

        # Esse bloco deseleciona qualquer seleção anterior, seleciona a feição escolhida e dá um zoom.
        camada.removeSelection()
        camada.selectByIds([id_feature])
        iface.mapCanvas().zoomToSelected(camada)

        # A escala é definida aqui, originalmente de 1:2500. A intenção é que esse valor também seja personalizável.
        # Testes apontaram que a escala de 1:2500 é suficiente para maioria dos casos, pois permite boa visualização dos arredores e não é tão próximo a ponto de dificultar a localização.
        escala_escolhida = 2500

        # Reajusta a escala para 1:2500, independente da escala original.
        if iface.mapCanvas().scale() < escala_escolhida:
            iface.mapCanvas().zoomScale(escala_escolhida)

        # Pisca a feição para facilitar sua localização, mesmo que o zoom já esteja centrado nela.
        # A base de dados pode possuir vários pontos extremamente próximos, então o destaque visual é útil na hora de
        # localizar a feição correta.
        iface.mapCanvas().flashFeatureIds(camada, [id_feature], duration=1000)

    # Ferramenta de seleção de rios, permitindo que ele seja selecionado diretamente no mapa.
    def ativar_selecao_rio(self):
        # Define a camada de rios a partir da seleção do usuário. Se a camada selecionada não for válida, uma mensagem aparece.
        camada_rios = self.sel_camada_rio.currentLayer()

        if not camada_rios:
            iface.messageBar().pushMessage("Erro", "Selecione uma camada de rios válida.", level=3)
            return
        if camada_rios.type() != QgsMapLayerType.VectorLayer:
            iface.messageBar().pushMessage("Erro", "A camada selecionada deve ser do tipo vetor.", level=3)
            return
        campos = camada_rios.fields()
        if campos.indexOf("cocursodag") == -1 or campos.indexOf("cobacia") == -1 or campos.indexOf("noriocomp") == -1:
            iface.messageBar().pushMessage("Erro", "A camada selecionada deve conter os campos 'cocursodag', 'cobacia' e 'noriocomp'.", level=3)
            return
        
        self.ferramenta_selecao_rio = QgsMapToolIdentifyFeature(iface.mapCanvas(), camada_rios)
        self.ferramenta_selecao_rio.featureIdentified.connect(self.processar_selecao_rio)

        iface.mapCanvas().setMapTool(self.ferramenta_selecao_rio)
        
    def processar_selecao_rio(self, feature):
        codigo_rio = str(feature["cocursodag"])
        codigo_bac = str(feature["cobacia"])
        nome_rio = str(feature["noriocomp"])
        acont = str(feature["nuareacont"])
        amont = str(feature["nuareamont"])

        self.display_codigo_rio = codigo_rio
        iface.mapCanvas().unsetMapTool(self.ferramenta_selecao_rio)

        self.disp_nome_rio.setText(nome_rio)
        self.disp_cod_rio.setText(codigo_rio)
        self.disp_cod_bac.setText(codigo_bac)

        self.amont_atual = float(amont)
        self.acont_atual = float(acont)

        self.atualizar_calculos()

    def atualizar_calculos(self):
        if getattr(self, 'amont_atual', 0.0) == 0.0 or getattr(self, 'acont_atual', 0.0) == 0.0:
            self.disp_q95.setText("0 m³/h")
            self.disp_qoutorgavel.setText("0 m³/h")
            return
        try:
            
            self.pct_aprop = self.sel_area_prop.value() / 100
            amont = self.amont_atual
            acont = self.acont_atual
            self.porc_out = 0

            if self.radioBtn_100.isChecked():
                self.porc_out = 1
            elif self.radioBtn_80.isChecked():
                self.porc_out = 0.8
            else:
                self.porc_out = 0.5

            self.aprop = (amont - acont) + (acont * (self.pct_aprop))
            self.val_q95 = round(self.aprop * self.sel_qesp.value() * 3.6, 2)

            self.val_qoutorgavel = round(self.val_q95 * self.porc_out, 2)

            self.saldo_q = self.val_qoutorgavel - getattr(self, 'vazao_outorgada', 0.0)
            if hasattr(self, 'disp_qdisponivel'):
                self.disp_qdisponivel.setText(f"{self.saldo_q:.2f} m³/h")

                if self.saldo_q < 0:
                    self.disp_qdisponivel.setStyleSheet("color: red; font-weight: bold;")
                else:
                    self.disp_qdisponivel.setStyleSheet("color: darkgreen; font-weight: bold;")

            self.disp_amont.setText(str(round(self.aprop, 2))+" km²")
            self.disp_q95.setText(str(self.val_q95)+" m³/h")
            self.disp_qoutorgavel.setText(str(self.val_qoutorgavel)+" m³/h")

        except Exception as e:
            print(f"Erro ao atualizar cálculos: {e}")

    def analise_montante(self, codigo_rio, codigo_bacia):
        if not codigo_rio or not codigo_bacia:
            QtWidgets.QMessageBox.warning(self, "Erro", "Código de rio ou bacia não encontrado. Selecione um rio para análise de montante.")
            return
        
        layer_bacia = self.sel_camada_ottobacias.currentLayer()
        if not layer_bacia:
            QtWidgets.QMessageBox.warning(self, "Erro", "Selecione uma camada de bacias válida para análise de montante.")
            return

        lista_outorgas = []

        for i in range(self.sel_camada.count()):
            layer = self.sel_camada.layer(i)
            if layer:
                lista_outorgas.append(layer)

        if not layer_bacia or not lista_outorgas:
            QtWidgets.QMessageBox.warning(self, "Erro", "Camada de bacias ou camadas de outorgas não encontradas. Verifique suas seleções para análise de montante.")
            return

        self.dialogo_montante = DialogoMontante(layer_bacia, lista_outorgas, codigo_rio, codigo_bacia, self.disp_nome_rio.text().strip())
        self.dialogo_montante.calculo_concluido.connect(self.receber_vazao_montante)

        self.dialogo_montante.show()

    def receber_vazao_montante(self, vazao):
        self.vazao_outorgada = vazao
        self.disp_ja_out.setText(f"{vazao:.2f} m³/h")
        self.saldo_q = getattr(self, 'val_qoutorgavel', 0.0) - vazao

        if hasattr(self, 'disp_qdisponivel'):
            self.disp_qdisponivel.setText(f"{self.saldo_q:.2f} m³/h")

    def gerar_memorial(self, vazao_montante):
        if getattr(self, 'val_qoutorgavel', 0.0) == 0.0:
            QtWidgets.QMessageBox.warning(self, "Erro", "Selecione ao menos um corpo hídrico para gerar o memorial.")
            return

        self.saldo_q = self.val_qoutorgavel - vazao_montante

        texto_memorial = ( 
            f"Memorial descritivo de análise de montante\n\n"
            f"Corpo hídrico: {self.disp_nome_rio.text()}\n\n")
        if self.pct_aprop != 1:
            texto_memorial += (f"Área de montante: {self.amont_atual:.2f} km²\n"
                f"Para este caso foi adotado uma área proporcional da bacia de contribuição.\n"
                f"O percentual adotado foi de {self.pct_aprop*100:.0f}% da área de contribuição do trecho analisado, resultando em uma área proporcional de {self.aprop:.2f} km².\n"
            )
        else:
            texto_memorial += (f"Área de montante: {self.aprop:.2f} km²\n")
        texto_memorial += (
            f"Vazão de Referência Q95: {self.val_q95:.2f} m³/h\n"
            f"De acordo com a legislação e atos administrativos vigentes, a vazão outorgável no trecho analisado ({self.display_codigo_rio}) corresponde a {self.porc_out*100:.0f}% da vazão de referência\n"
            f"Vazão Outorgável: {self.val_qoutorgavel:.2f} m³/h\n"
            f"Vazão Outorgada a Montante: {vazao_montante:.2f} m³/h\n"
            f"Vazão Disponível e Outorgável: {self.saldo_q:.2f} m³/h\n\n"
            f"Q95 = {self.aprop:.2f} km² * {self.sel_qesp.value():.2f} L/s/km² * 3.6 = {self.val_q95:.2f} m³/h\n"
            f"Qoutorgável = {self.val_q95:.2f} m³/h * {self.porc_out*100:.0f}% = {self.val_qoutorgavel:.2f} m³/h\n"
            f"Qdisponível = {self.val_qoutorgavel:.2f} m³/h - {vazao_montante:.2f} m³/h = {self.saldo_q:.2f} m³/h"
            )
        
        if self.saldo_q < 0:
            texto_memorial += "\n\nObservação: A vazão outorgada a montante excede a vazão outorgável calculada, indicando que não há disponibilidade hídrica para novas outorgas nesse cenário."
        else:
            texto_memorial += "\n\nObservação: A vazão outorgada a montante é inferior à vazão outorgável calculada, indicando que há disponibilidade hídrica para novas outorgas nesse cenário."

        texto_memorial += "\n\nEste memorial foi gerado automaticamente, considerando os dados disponíveis na base de dados do Instituto.\n\nO técnico deverá conferir as informações contra a análise conjunta quando possível."

        popup = QtWidgets.QDialog(self)
        popup.setWindowTitle("Memorial Descritivo")
        popup.resize(550, 400)

        layout = QtWidgets.QVBoxLayout(popup)

        caixa_texto = QtWidgets.QTextEdit(popup)
        caixa_texto.setReadOnly(True)
        caixa_texto.setText(texto_memorial)
        layout.addWidget(caixa_texto)

        btn_fechar = QtWidgets.QPushButton("Fechar", popup)
        btn_fechar.clicked.connect(popup.accept)
        layout.addWidget(btn_fechar)

        popup.exec_()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

class DialogoMontante(QtWidgets.QDialog, DIALOG_CLASS):

    calculo_concluido = pyqtSignal(float)
    def __init__(self, layer_bacia, lista_outorgas, cod_rio, cod_bac, nome_rio, parent=None):
        super(DialogoMontante, self).__init__(parent)
        self.setupUi(self)

        self.layer_bacia = layer_bacia
        self.lista_outorgas = lista_outorgas
        self.cod_rio = cod_rio
        self.cod_bac = cod_bac
        self.nome_rio = nome_rio

        self.tabela_resMont.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabela_resMont.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        self.btn_exec.clicked.connect(self.executar_cruzamento)
        self.btn_cop.clicked.connect(self.copiar_resultados)

    def buscar_valor_campo(self, feature, lista_nomes):
        for nome in lista_nomes:
            idx = feature.fieldNameIndex(nome)
            if idx != -1:
                valor = feature[nome]
                val_str = str(valor).strip().upper()

                if valor is not None and val_str not in ["", "NULL", "NONE"]:
                    return valor
        return None
        
    def executar_cruzamento(self):
        expressao = f"\"cocursodag\" LIKE '{self.cod_rio}%' and \"cobacia\" >= '{self.cod_bac}'"
        req_bacias = QgsFeatureRequest().setFilterExpression(expressao)

        geom_montante = QgsGeometry()
        for f in self.layer_bacia.getFeatures(req_bacias):
            if geom_montante.isNull():
                geom_montante = f.geometry()
            else:
                geom_montante = geom_montante.combine(f.geometry())

        if geom_montante.isNull():
            QtWidgets.QMessageBox.warning(self, "Erro", "Não foi possível determinar a geometria de montante para o rio selecionado.")
            return

        crs_bacia = self.layer_bacia.crs()

        nome_camada = f"Montante_{self.cod_rio}_{self.cod_bac}_{self.nome_rio}".strip().replace(" ", "_")
        camada_montante = QgsVectorLayer("Polygon", nome_camada, "memory")
        camada_montante.setCrs(crs_bacia)

        provedor = camada_montante.dataProvider()
        feature_debug = QgsFeature()
        feature_debug.setGeometry(geom_montante)
        provedor.addFeatures([feature_debug])
        camada_montante.updateExtents()

        simbolo = QgsSymbol.defaultSymbol(camada_montante.geometryType())
        simbolo.setColor(QtGui.QColor(255, 0, 0, 75))
        simbolo.symbolLayer(0).setStrokeColor(QtGui.QColor(255, 0, 0))
        simbolo.symbolLayer(0).setStrokeWidth(0.5)

        camada_montante.setRenderer(QgsSingleSymbolRenderer(simbolo))

        QgsProject.instance().addMapLayer(camada_montante, False)
        root = QgsProject.instance().layerTreeRoot()
        root.insertLayer(0, camada_montante)

        self.tabela_resMont.setRowCount(0)

        self.tabela_resMont.setColumnCount(4)
        self.tabela_resMont.setHorizontalHeaderLabels(["Portaria/Protocolo", "Razão Social", "Finalidades", "Vazão Outorgada (m³/h)"])

        header = self.tabela_resMont.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QHeaderView.Stretch)

        linha = 0
        vaz_tot = 0.0

        for layer in self.lista_outorgas:
            nome_layer = layer.name().upper()
            possui_vazao = layer.fields().indexOf("vlr_vazao_capt_lanc_jan") != -1 or layer.fields().indexOf("VAZAO_OUTORGADA_M3_H") != -1

            if "AIA" in nome_layer or "Áreas autuadas/embargadas" in nome_layer or not possui_vazao:
                continue
            req_outorgas = QgsFeatureRequest().setFilterRect(geom_montante.boundingBox())

            for outorga in layer.getFeatures(req_outorgas):
                if geom_montante.contains(outorga.geometry()) or outorga.geometry().intersects(geom_montante):
                    tipo_poco = self.buscar_valor_campo(outorga, ["desc_tipo_poco", "DESC_TIPO_POCO", "tipo_poco", "TIPO_POCO", "tipo_manancial", "TIPO_MANANCIAL"])
                    if tipo_poco is not None and str(tipo_poco).strip() != "" and str(tipo_poco).strip() != "NULL":
                        continue
                    portaria = self.buscar_valor_campo(outorga, ["nr_portaria", "PORTARIA"])
                    protocolo = self.buscar_valor_campo(outorga, ["nr_e_protocolo", "PROTOCOLO"])
                    requerente = self.buscar_valor_campo(outorga, ["nm_requerente", "RAZAOSOCIAL"])
                    finalidade = self.buscar_valor_campo(outorga, ["desc_finalidades", "FINALIDADES"])
                    vazao_diluicao = self.buscar_valor_campo(outorga, ["vlr_vazao_diluicao_jan"])

                    if vazao_diluicao is not None and float(vazao_diluicao) > 0:
                        try:
                            vazao_str = str(vazao_diluicao).replace(",", ".").strip()
                            vazao = float(vazao_str)
                        except (ValueError, TypeError):
                            vazao = 0.0
                    else:
                        vazao_raw = self.buscar_valor_campo(outorga, ["vlr_vazao_capt_lanc_jan", "VAZAO_OUTORGADA_M3_H"])
                        try:
                            vazao_str = str(vazao_raw).replace(",", ".").strip() if vazao_raw is not None else "0"
                            vazao = float(vazao_str)
                        except (ValueError, TypeError):
                            vazao = 0.0
                    

                    if portaria is not None and portaria != "":
                        str_portaria = str(portaria)
                        portariaExistente = True
                    elif protocolo is not None and protocolo != "":
                        str_portaria = "N/A"
                        portariaExistente = False
                    else:
                        continue

                    vaz_tot += vazao
                    self.tabela_resMont.insertRow(linha)
                    match portariaExistente:
                        case True:
                            self.tabela_resMont.setItem(linha, 0, QTableWidgetItem(str_portaria))
                        case False:
                            self.tabela_resMont.setItem(linha, 0, QTableWidgetItem(str(protocolo)))
                    self.tabela_resMont.setItem(linha, 1, QTableWidgetItem(str(requerente)))
                    self.tabela_resMont.setItem(linha, 2, QTableWidgetItem(str(finalidade)))
                    self.tabela_resMont.setItem(linha, 3, QTableWidgetItem(f"{vazao:.2f}"))
                    linha += 1

        vaz_tot = round(vaz_tot, 2)
        self.tabela_resMont.insertRow(linha)
        self.tabela_resMont.setItem(linha, 0, QTableWidgetItem("Vazão Total"))
        self.tabela_resMont.setItem(linha, 3, QTableWidgetItem(f"{vaz_tot:.2f} m³/h"))

        self.calculo_concluido.emit(vaz_tot)

    def copiar_resultados(self):
        num_linhas = self.tabela_resMont.rowCount()
        num_colunas = self.tabela_resMont.columnCount()

        resultados_texto = ""

        headers = []
        for col in range(num_colunas):
            item_header = self.tabela_resMont.horizontalHeaderItem(col)
            headers.append(item_header.text() if item_header else f"Coluna {col}")

        resultados_texto += "\t".join(headers) + "\n"

        for linha in range (num_linhas):
            valores_linha = []
            for col in range(num_colunas):
                item = self.tabela_resMont.item(linha, col)
                valor = item.text() if item else ""
                valores_linha.append(valor)

            resultados_texto += "\t".join(valores_linha) + "\n"

        QtWidgets.QApplication.clipboard().setText(resultados_texto)
        iface.messageBar().pushMessage("Sucesso", "Resultados copiados para a área de transferência.", level=0, duration=3)

    def closeEvent(self, event):
        event.accept()