# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iat_teste_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IatTesteDockWidgetBase(object):
    def setupUi(self, IatTesteDockWidgetBase):
        IatTesteDockWidgetBase.setObjectName("IatTesteDockWidgetBase")
        IatTesteDockWidgetBase.resize(520, 467)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.sel_camada = gui.QgsMapLayerComboBox(self.dockWidgetContents)
        self.sel_camada.setEditable(True)
        self.sel_camada.setObjectName("sel_camada")
        self.gridLayout.addWidget(self.sel_camada, 0, 0, 1, 1)
        self.sel_campo = QtWidgets.QComboBox(self.dockWidgetContents)
        self.sel_campo.setObjectName("sel_campo")
        self.sel_campo.addItem("")
        self.sel_campo.addItem("")
        self.sel_campo.addItem("")
        self.gridLayout.addWidget(self.sel_campo, 1, 0, 1, 1)
        self.btn_exec = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_exec.setObjectName("btn_exec")
        self.gridLayout.addWidget(self.btn_exec, 2, 1, 1, 1)
        self.valor_pesq = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.valor_pesq.setObjectName("valor_pesq")
        self.gridLayout.addWidget(self.valor_pesq, 2, 0, 1, 1)
        self.tabela = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(0)
        self.tabela.setRowCount(0)
        self.gridLayout.addWidget(self.tabela, 3, 0, 1, 1)
        IatTesteDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(IatTesteDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(IatTesteDockWidgetBase)

    def retranslateUi(self, IatTesteDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        IatTesteDockWidgetBase.setWindowTitle(_translate("IatTesteDockWidgetBase", "IatTeste"))
        self.sel_campo.setItemText(0, _translate("IatTesteDockWidgetBase", "Protocolo"))
        self.sel_campo.setItemText(1, _translate("IatTesteDockWidgetBase", "Nome"))
        self.sel_campo.setItemText(2, _translate("IatTesteDockWidgetBase", "CPF/CNPJ"))
        self.btn_exec.setText(_translate("IatTesteDockWidgetBase", "Pesquisar"))
from qgis import gui
