# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IatTesteDockWidget
                                 A QGIS plugin
 Este plugin serve para facilitar o workflow das análises no âmbito do Instituto.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by IAT
        email                : est.pedromoraes@iat.pr.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import QgsFeatureRequest, QgsMapLayerProxyModel, QgsMapLayerType
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtWidgets import QTableWidgetItem, QHeaderView
from qgis.PyQt.QtCore import pyqtSignal
from qgis.utils import iface

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'iat_teste_dockwidget_base.ui'))


class IatTesteDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(IatTesteDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.btn_exec.setDefault(True)

        self.sel_camada.setFilters(QgsMapLayerProxyModel.VectorLayer)

        self.btn_exec.clicked.connect(self.executar_analise)
        self.valor_pesq.returnPressed.connect(self.executar_analise)

        self.tabela.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabela.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabela.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabela.setColumnHidden(0, True)
        self.tabela.cellDoubleClicked.connect(self.zoom_pto)

    def executar_analise(self):
        texto_pesquisa = self.valor_pesq.text().strip()
        tipo_filtro = self.sel_campo.currentText()
        camada = self.sel_camada.currentLayer()

        if not camada:
            QtWidgets.QMessageBox.warning(self, "Erro", "Selecione uma camada válida.")
            return
        if camada.type() != QgsMapLayerType.VectorLayer:
            QtWidgets.QMessageBox.warning(self, "Erro", "A camada selecionada deve ser do tipo pontos ou vetor.")
            return
        if not texto_pesquisa:
            QtWidgets.QMessageBox.warning(self, "Erro", "Digite um valor para pesquisa.")
            return

        if tipo_filtro in ["CPF/CNPJ","Protocolo"]:
                texto_limpo = texto_pesquisa.replace(".", "").replace("-", "").replace("/", "")
        else:
                texto_limpo = texto_pesquisa

        campo_selecionado = ""
        if tipo_filtro == "CPF/CNPJ":
            campo_selecionado = "nr_cpf_cnpj"
        elif tipo_filtro == "Protocolo":
            campo_selecionado = "nr_e_protocolo"
        elif tipo_filtro == "Nome":
            campo_selecionado = "nm_requerente"
        elif tipo_filtro == "Portaria":
            campo_selecionado = "nr_portaria"

        expressao = f"\"{campo_selecionado}\" ILIKE '%{texto_limpo}%'"
        print(f"Expressão de filtro: {expressao}")

        request = QgsFeatureRequest().setFilterExpression(expressao)
        features = camada.getFeatures(request)

        self.tabela.setColumnCount(5)
        self.tabela.setHorizontalHeaderLabels(["ID", "CPF/CNPJ", "Protocolo", "Nome", "Portaria"])

        header = self.tabela.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QHeaderView.Interactive)
        header.setSectionResizeMode(3, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QHeaderView.Stretch)

        self.tabela.setRowCount(0)
        linha = 0

        encontrou_resultados = False

        for feature in features:
            encontrou_resultados = True
            id_feature = str(feature.id())

            val_cpf_cnpj = str(feature["nr_cpf_cnpj"])
            val_protocolo = str(feature["nr_e_protocolo"])
            val_nome = str(feature["nm_requerente"])
            val_portaria = str(feature["nr_portaria"])

            self.tabela.insertRow(linha)
            self.tabela.setItem(linha, 0, QTableWidgetItem(id_feature))
            self.tabela.setItem(linha, 1, QTableWidgetItem(val_cpf_cnpj))
            self.tabela.setItem(linha, 2, QTableWidgetItem(val_protocolo))
            self.tabela.setItem(linha, 3, QTableWidgetItem(val_nome))
            self.tabela.setItem(linha, 4, QTableWidgetItem(val_portaria))

            linha += 1

        if not encontrou_resultados:
            QtWidgets.QMessageBox.information(self, "Resultados", "Nenhum resultado encontrado.")

    def zoom_pto(self, linha, coluna):
        camada = self.sel_camada.currentLayer()
        if not camada:
            return
        
        id_item = self.tabela.item(linha, 0)
        if not id_item:
            return

        id_feature = int(id_item.text())

        camada.removeSelection()
        camada.selectByIds([id_feature])
        iface.mapCanvas().zoomToSelected(camada)

        escala_escolhida = 2500

        if iface.mapCanvas().scale() < escala_escolhida:
            iface.mapCanvas().zoomScale(escala_escolhida)

        iface.mapCanvas().flashFeatureIds(camada, [id_feature], duration=1000)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
